{% set name = "pycrdt-store" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 12a0e263b2c07eb18bbe7203c828b88ba953cb93094ad37d22aeb6c619df2ef0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - anyio >=3.6.2,<5
    - sqlite-anyio >=0.2.3,<0.3.0
    - pycrdt >=0.12.13,<0.13.0

test:
  source_files:
    - tests
  imports:
    - pycrdt.store
  requires:
    - pip
    - pytest
    - trio
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/y-crdt/pycrdt-store
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Persistent storage for pycrdt
  description: Persistent storage for pycrdt.
  dev_url: https://github.com/y-crdt/pycrdt-store
  doc_url: https://github.com/y-crdt/pycrdt-store/blob/main/README.md

extra:
  recipe-maintainers:
    - davidbrochart